# Generated by Django 3.0.7 on 2020-07-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='professors',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='students',
            name='admin',
        ),
        migrations.AddField(
            model_name='college',
            name='usertypes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professors',
            name='usertypes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='usertypes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.CustomUser'),
            preserve_default=False,
        ),
    ]
